create sequence seq_persona;
create table t_animals (ani_nom varchar(255) not null, ani_propietari bigint, primary key (ani_nom));
create table t_cases (cas_id bigint generated by default as identity, cas_adreca varchar(255), cas_municipi varchar(255), cas_propietari bigint, primary key (cas_id));
create table t_municipis (mun_nom varchar(255) not null, primary key (mun_nom));
create table t_persones (per_id bigint not null, per_nom varchar(255), primary key (per_id));
alter table t_animals add constraint propietari_animal_fk foreign key (ani_propietari) references t_persones;
alter table t_cases add constraint municipi_fk foreign key (cas_municipi) references t_municipis;
alter table t_cases add constraint propietari_casa foreign key (cas_propietari) references t_persones;